# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Alfredo Sanchez, Jr.
title: Head of IT @ Avega Bros
email: derf@sanchez.ph
# email_title: Email (Email title override)
phone: (917) 702-5960
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: tildemark
linkedin_username: tildemark
facebook_username: tildemark

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Results-driven IT leader with extensive experience in maritime and land-based technology deployments at Avega Bros Integrated Shipping Corp. Proven ability to manage complex IT projects, including ERP development, network infrastructure, IOT, and renewable energy solutions. Dual role as Data Protection Officer, ensuring data privacy compliance. 
  
  I am most skilled in: <mark>ERP</mark>, <mark>IOT</mark> and <mark>Project Management</mark>

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  #   - Lists
  #   - Tables
  #   - <a href="google.com">Links</a>
  #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects
    layout: list
    content:
      - layout: right
        title: GreenStone Farm Credit Services
        sub_title: Service Desk Intern
        caption: May 2023 - August 2023
        link: https://www.greenstonefcs.com/
        quote: >
          East Lansing, MI
        description: | # this will include new lines to allow paragraphs
          Managed and provided daily operations of troubleshooting calls, offering exceptional technical assistance to multiple departments in 35 locations throughout Michigan and Northeast Wisconsin.
          Organized and executed a large-scale phone replacement project for 120 employees by preplanning and analyzing logistics, confirming a seamless transition and minimal disruption to workflow during the phone upgrade.
          Demonstrated proficiency in operating and bolstering critical IT infrastructure, including Azure Active Directory, Secret Server, and Office 365 platforms, assuring access and security controls for a large user base.

      - layout: right
        title: MSU College of Engineering
        sub_title: Undergraduate Researcher
        caption: September 2022 - Present
        link: https://slim-msu.github.io/
        quote: >
          East Lansing, MI
        description: | # this will include new lines to allow paragraphs
          Selected for a highly selective program dedicated to the top 1% of incoming freshmen to conduct undergraduate research in a group of like-minded students, focusing on computational imaging and machine learning subjects.
          Analyze EEG data for a mantra meditation study with 23 subjects, revealing improved cognition in young adults and resulting in the submission and acceptance of an abstract to the Society for Neuroscience.
          Created and now survey the research team's dynamic website, disseminating complex technical concepts to a large audience, promoting 25 monthly contact submissions, and blocking 80% of reCAPTCHA suspicious requests.


  - title: Experience
    layout: list
    content:
      - layout: right
        title: GreenStone Farm Credit Services
        sub_title: Service Desk Intern
        caption: May 2023 - August 2023
        link: https://www.greenstonefcs.com/
        quote: >
          East Lansing, MI
        description: | # this will include new lines to allow paragraphs
          Managed and provided daily operations of troubleshooting calls, offering exceptional technical assistance to multiple departments in 35 locations throughout Michigan and Northeast Wisconsin.
          Organized and executed a large-scale phone replacement project for 120 employees by preplanning and analyzing logistics, confirming a seamless transition and minimal disruption to workflow during the phone upgrade.
          Demonstrated proficiency in operating and bolstering critical IT infrastructure, including Azure Active Directory, Secret Server, and Office 365 platforms, assuring access and security controls for a large user base.

      - layout: right
        title: MSU College of Engineering
        sub_title: Undergraduate Researcher
        caption: September 2022 - Present
        link: https://slim-msu.github.io/
        quote: >
          East Lansing, MI
        description: | # this will include new lines to allow paragraphs
          Selected for a highly selective program dedicated to the top 1% of incoming freshmen to conduct undergraduate research in a group of like-minded students, focusing on computational imaging and machine learning subjects.
          Analyze EEG data for a mantra meditation study with 23 subjects, revealing improved cognition in young adults and resulting in the submission and acceptance of an abstract to the Society for Neuroscience.
          Created and now survey the research team's dynamic website, disseminating complex technical concepts to a large audience, promoting 25 monthly contact submissions, and blocking 80% of reCAPTCHA suspicious requests.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of the Philippines Open University (UPOU)
        sub_title: Master of Information Systems (MIS) - credit units
        caption: Los Baños, Laguna
        # quote: >
        #  Los Baños, Laguna 
        description: | # this will include new lines to allow paragraphs
          Advanced study in information systems management, focusing on strategic IT planning and data management.

      - layout: left
        title: Notre Dame of Dadiangas University (NDDU)
        sub_title: Master of Business Administration (MBA) - credit units
        caption: General Santos City
        #quote: >
        #  General Santos City
        description: | # this will include new lines to allow paragraphs
          Developed business acumen in areas such as financial analysis, strategic planning, and organizational leadership.

      - layout: left
        title: Mindanao Polytechnic State College (MPSC)
        sub_title: Bachelor of Science in Computer Engineering 
        caption: Cagayan de Oro City
        #quote: >
        #  Cagayan de Oro City
        description: | # this will include new lines to allow paragraphs
          Gained a strong foundation in computer hardware and software principles, including network design and systems architecture.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]